export const buildings = [
  {
    name: 'Cité radieuse',
    city: 'Marseille',
    id: 'cr1',
    imgUrl: '/img/cr1/cite-radieuse.png',
    width: 624,
    height: 432,
    details: [
      {
        type: 'img',
        imgUrl: '/img/cr1/cite-radieuse.png',
        order: 1,
        width: 624,
        height: 432,
        alt: 'top',
      },
      {
        type: 'img',
        imgUrl: '/img/cr1/front.png',
        order: 2,
        width: 655,
        height: 438,
        alt: 'front',
      },
      {
        type: 'text',
        text: 'Le Corbusier collaborated with the painter-architect Nadir Afonso on this modernist Unité d’Habitation housing block in Marseilles, France. The bréton brut (rough-cast concrete) of the building partly inspired the name Brutalism.',
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/cr1/pillar.png',
        order: 4,
        width: 663,
        height: 438,
        alt: 'pillar',
      },
      {
        type: 'img',
        imgUrl: '/img/cr1/vert.png',
        order: 5,
        width: 283,
        height: 483,
        alt: 'vertical',
      },
    ],
  },
  {
    name: 'The Barbarican Estate',
    city: 'London',
    id: 'be1',
    imgUrl: '/img/be1/barbarican-estate.png',
    width: 528,
    height: 336,
    details: [
      {
        type: 'img',
        imgUrl: '/img/be1/barbarican-estate.png',
        width: 528,
        height: 336,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/be1/over.png',
        order: 2,

        width: 1464,
        height: 978,
      },
      {
        type: 'text',
        text: 'The bombing raids of the Second World War largely destroyed the City of London, but also presented an opportunity to post-war architects. The Barbican was a radical reimagining of what urban areas could look like, however it failed to catch on.',
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/be1/vert.png',
        order: 4,
        width: 440,
        height: 620,
      },
    ],
  },
  {
    name: 'Habitat 67',
    city: 'Montreal',
    id: 'h67',
    imgUrl: '/img/h67/habitat-67.png',
    width: 576,
    height: 384,
    details: [
      {
        type: 'img',
        imgUrl: '/img/h67/habitat-67.png',
        width: 576,
        height: 384,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/h67/inside.png',
        order: 2,
        width: 786,
        height: 541,
      },
      {
        type: 'text',
        text: "Moshe Safdie originally designed this housing unit for his master's thesis. It was constructed for Expo 67, the 1967 World's Fair, when he was just 29. Its unusual design captured imaginations and fired indignation.",
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/h67/overview.png',
        order: 4,
        width: 539,
        height: 745,
      },
    ],
  },
  {
    name: 'Boston City Hall',
    city: 'Boston',
    id: 'bch',
    imgUrl: '/img/bch/boston-city-hall.png',
    width: 366,
    height: 480,
    details: [
      {
        type: 'img',
        imgUrl: '/img/bch/boston-city-hall.png',
        width: 366,
        height: 480,
        order: 1,
      },
      {
        type: 'text',
        text: 'This seat of city government is perhaps the most controversial in the United States. Before the building was completed there were demands for it to be demolished. However, architects and critics have repeatedly praised the structure, describing it as one of the finest in the US.',
        order: 2,
      },
      {
        type: 'img',
        imgUrl: '/img/bch/inside.png',
        order: 3,
        width: 1051,
        height: 709,
      },
    ],
  },
  {
    name: 'Alexandra Road Estate',
    city: 'London',
    id: 'are',
    imgUrl: '/img/are/alexandra-road-estate.png',
    width: 480,
    height: 336,
    details: [
      {
        type: 'img',
        imgUrl: '/img/are/alexandra-road-estate.png',
        width: 480,
        height: 336,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/are/front.png',
        order: 2,
        width: 550,
        height: 620,
      },
      {
        type: 'text',
        text: 'The ziggurat-form of this terraced housing in Camden, London, presents an alternative to high rise tower blocks. Architect Neave Brown thought that the low-rise houses, with their own front doors and gardens, would feel safer and more private.',
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/are/old.png',
        order: 4,
        width: 1041,
        height: 823,
      },
    ],
  },
  {
    name: 'Tanghalang Pambansa',
    city: 'Milan',
    id: 'tp1',
    imgUrl: '/img/tp1/tanghalang-pambansa.png',
    width: 528,
    height: 384,
    details: [
      {
        type: 'img',
        imgUrl: '/img/tp1/tanghalang-pambansa.png',
        width: 528,
        height: 384,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/tp1/right.png',
        order: 2,
        width: 500,
        height: 647,
      },
      {
        type: 'text',
        text: "This building, Leandro Locsin's national theatre of the Philippines, combines European ideals of minimalist modernism with structures found in indigenous architecture, such as the raised living space of the nipa hut.",
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/tp1/front.png',
        order: 4,
        width: 1289,
        height: 639,
      },
    ],
  },
  {
    name: 'Preston Bus Station',
    city: 'Preston',
    id: 'pss',
    imgUrl: '/img/pss/preston-bus-station.png',
    width: 528,
    height: 528,
    details: [
      {
        type: 'img',
        imgUrl: '/img/pss/preston-bus-station.png',
        width: 528,
        height: 528,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/pss/inside.png',
        order: 2,
        width: 1499,
        height: 1000,
      },
      {
        type: 'text',
        text: 'Many brutalist buildings face uncertain futures. Preston Bus Station was threatened with demolition for decades. After many unsuccessful campaigns to have the bus station given legal protection, a protection order was finally granted in 2013.',
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/pss/coolpic.png',
        order: 4,
        width: 600,
        height: 600,
      },
    ],
  },
  {
    name: 'Geisel Library',
    city: 'La Jolla',
    id: 'gl1',
    imgUrl: '/img/gl1/geisel-library.png',
    width: 440,
    height: 600,
    details: [
      {
        type: 'img',
        imgUrl: '/img/gl1/geisel-library.png',
        width: 440,
        height: 600,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/gl1/front.png',
        order: 2,
        width: 1321,
        height: 903,
      },
      {
        type: 'text',
        text: 'The Geisel Library opened at the University of California San Diego in 1970. The library is a spheroid shape, designed by William Pereira to reduce the time taken travelling from the centre to any other part of the building.',
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/gl1/black.png',
        order: 4,
        width: 500,
        height: 666,
      },
    ],
  },
  {
    name: 'Trellick Tower',
    city: 'London',
    id: 'tt1',
    imgUrl: '/img/tt1/trellick-tower.png',
    width: 384,
    height: 528,
    details: [
      {
        type: 'img',
        imgUrl: '/img/tt1/trellick-tower.png',
        width: 384,
        height: 528,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/tt1/down.png',
        order: 2,
        width: 600,
        height: 600,
      },
      {
        type: 'text',
        text: "Architect Ernő Goldfinger designed Trellick Tower using the feedback from his earlier Balfron Tower. However it was completed just as brutalist high rises were falling out of fashion, it's fair to say that it's more popular now than at any previous point.",
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/tt1/far.png',
        order: 4,
        width: 1486,
        height: 1069,
      },
    ],
  },
  {
    name: 'Rozzol Malera',
    city: 'Trieste',
    id: 'rm1',
    imgUrl: '/img/rm1/rozzol-melara.png',
    width: 624,
    height: 432,
    details: [
      {
        type: 'img',
        imgUrl: '/img/rm1/rozzol-melara.png',
        width: 624,
        height: 432,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/rm1/front.png',
        order: 2,
        width: 732,
        height: 600,
      },
      {
        type: 'text',
        text: 'Sited on a hillside on the eastern edge of the city, the apartments of Rozzol Melara look out over the Adriatic Sea. While a lot of consideration went into the architecture, the estate has been plagued by mismanagement.',
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/rm1/left.png',
        order: 4,
        width: 370,
        height: 600,
      },
    ],
  },
  {
    name: 'Buffalo City Court Building',
    city: 'Buffalo',
    id: 'bccb',
    imgUrl: '/img/bccb/buffalo-city.png',
    width: 710,
    height: 400,
    details: [
      {
        type: 'img',
        imgUrl: '/img/bccb/buffalo-city.png',
        width: 710,
        height: 400,
        order: 1,
      },
      {
        type: 'img',
        imgUrl: '/img/bccb/overview.png',
        width: 650,
        height: 600,
        order: 2,
      },
      {
        type: 'text',
        text: "The striking, blank concrete panels and razor thin windows of this US court building were designed to reduce the possibility of distraction for the judges and clerks working within, bringing a new meaning to 'justice is blind'.",
        order: 3,
      },
      {
        type: 'img',
        imgUrl: '/img/bccb/topside.png',
        width: 434,
        height: 600,
        order: 4,
      },
    ],
  },
]

export const info = {
  text: 'The New Brutalism\' is an experimental website inspired from an article from 1955, \'The New Brutalism\', by Reyner Banham. This is my own personal experimentation with draggable map overlay which translates to the second idea of "brutalist" structure - "Clear exhibition of structure". This website includes brief information, pictures about 11 structures from all around the world which influences and resembles the brutalist movement the most. The website design was my own interpretation of brutalist structure into web application. It might be misunderstood as a minimalist approach, but in essence the brutalism was about efficiency, valuation of raw materials. Brutalism is often seen as an anti-design but it is instead form of expression of raw, brutally honest design.',
}
